package com.thecalcurate.android.model

data class CurrencyItem(
    val name: String,
    val code: String
) {
    companion object {
        fun getList(): MutableList<CurrencyItem> {
            var currencyItemList: MutableList<CurrencyItem> = ArrayList()
            currencyItemList.add(CurrencyItem("🇺🇸 USA Dollar", "USD"))
            currencyItemList.add(CurrencyItem("🇪🇺 Euro", "AED"))
            currencyItemList.add(CurrencyItem("🇬🇧 British Pound", "BRP"))
            currencyItemList.add(CurrencyItem("🇦🇫 Afghan Afghani", "AED"))
            currencyItemList.add(CurrencyItem("🇦🇱 Albanian Lek", "AED"))
            currencyItemList.add(CurrencyItem("🇩🇿 Algerian Dinar", "AED"))
            currencyItemList.add(CurrencyItem("🇦🇴 Angolan Kwanza", "AED"))
            currencyItemList.add(CurrencyItem("🇦🇷 Argentine Peso", "AED"))
            currencyItemList.add(CurrencyItem("🇦🇲 Armenian Dram", "AED"))
            currencyItemList.add(CurrencyItem("🇦🇼 Aruban Florin", "AED"))
            currencyItemList.add(CurrencyItem("🇦🇺 Australian Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇦🇿 Azerbaijani Manat", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇸 Bahamian Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇭 Bahraini Dinar", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇩 Bangladeshi Taka", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇧 Barbadian Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇾 Belarusian Ruble", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇿 Belize Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇲 Bermudan Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇹 Bhutanese Ngultrum", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇴 Bolivian Boliviano", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇷 Brazilian Real", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇳 Brunei Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇬 Bulgarian Lev", "AED"))
            currencyItemList.add(CurrencyItem("🇧🇮 Burundian Franc", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇫 Central African Franc", "AED"))
            currencyItemList.add(CurrencyItem("🇰🇭 Cambodian Riel", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇦 Canadian Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇻 Cape Verdean Escudo", "AED"))
            currencyItemList.add(CurrencyItem("🇰🇾 Cayman Island Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇿 Czech Koruna", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇱 Chilean Peso", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇳 Chinese Yuan", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇴 Colombian Peso", "AED"))
            currencyItemList.add(CurrencyItem("🇰🇲 Comorian Franc", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇩 Congolese Franc", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇷 Costa Rican Colon", "AED"))
            currencyItemList.add(CurrencyItem("🇭🇷 Croatian Kuna", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇺 Cuban Peso", "AED"))
            currencyItemList.add(CurrencyItem("🇩🇰 Danish Krone", "AED"))
            currencyItemList.add(CurrencyItem("🇩🇯 Djiboutian Franc", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇹 Dobra", "AED"))
            currencyItemList.add(CurrencyItem("🇩🇴 Dominican Peso", "AED"))
            currencyItemList.add(CurrencyItem("🇦🇬 East Caribbean Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇪🇬 Egyptian Pound", "AED"))
            currencyItemList.add(CurrencyItem("🇪🇷 Eritrean Nakfa", "AED"))
            currencyItemList.add(CurrencyItem("🇪🇹 Ethiopian Birr", "AED"))
            currencyItemList.add(CurrencyItem("🇫🇯 Fijian Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇬🇲 Gambian Dalasi", "AED"))
            currencyItemList.add(CurrencyItem("🇬🇪 Georgian Lari", "AED"))
            currencyItemList.add(CurrencyItem("🇬🇭 Ghanaian Cedi", "AED"))
            currencyItemList.add(CurrencyItem("🇬🇮 Girbaltar Pound", "AED"))
            currencyItemList.add(CurrencyItem("🇬🇹 Guatemalan Quetzal", "AED"))
            currencyItemList.add(CurrencyItem("🇬🇳 Guinean Franc", "AED"))
            currencyItemList.add(CurrencyItem("🇬🇾 Guyanaese Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇭🇰 Hong Kong Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇭🇹 Haitian Gourde", "AED"))
            currencyItemList.add(CurrencyItem("🇭🇳 Honduran Lempira", "AED"))
            currencyItemList.add(CurrencyItem("🇭🇺 Hungarian Forint", "AED"))
            currencyItemList.add(CurrencyItem("🇮🇸 Iceland Króna", "AED"))
            currencyItemList.add(CurrencyItem("🇮🇳 Indian Rupee", "AED"))
            currencyItemList.add(CurrencyItem("🇮🇩 Indonesian Rupiah", "AED"))
            currencyItemList.add(CurrencyItem("🇮🇷 Iranian Rial", "AED"))
            currencyItemList.add(CurrencyItem("🇮🇶 Iraqi Dinar", "AED"))
            currencyItemList.add(CurrencyItem("🇮🇱 Israeli Shekel", "AED"))
            currencyItemList.add(CurrencyItem("🇯🇲 Jamaican Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇯🇴 Jordanian Dinar", "AED"))
            currencyItemList.add(CurrencyItem("🇯🇵 Japanese Yen", "AED"))
            currencyItemList.add(CurrencyItem("🇰🇿 Kazakhstani Tenge", "AED"))
            currencyItemList.add(CurrencyItem("🇰🇪 Kenyan Shilling", "AED"))
            currencyItemList.add(CurrencyItem("🇰🇼 Kuwaiti Dinar", "AED"))
            currencyItemList.add(CurrencyItem("🇰🇬 Kyrgystani Som", "AED"))
            currencyItemList.add(CurrencyItem("🇱🇦 Laotian Kip", "AED"))
            currencyItemList.add(CurrencyItem("🇱🇧 Lebanese Pound", "AED"))
            currencyItemList.add(CurrencyItem("🇱🇷 Liberian Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇱🇾 Libyan Dinar", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇰 Macedonian Denar", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇬 Malagasy Ariary", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇼 Malawian Kwacha", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇾 Malaysian Ringgit", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇻 Maldivian Rufiyaa", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇺 Mauritian Rupee", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇷 Mauritanian Ouguiya", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇽 Mexican Peso", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇩 Moldovan Leu", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇳 Mangolian Tugrik", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇦 Moroccan Dirham", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇿 Mozambican Metical", "AED"))
            currencyItemList.add(CurrencyItem("🇲🇲 Myanmar Kyat", "AED"))
            currencyItemList.add(CurrencyItem("🇳🇿 New Zealand Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇳🇦 Nambian Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇳🇵 Nepalese Rupee", "AED"))
            currencyItemList.add(CurrencyItem("🇳🇱 Netherlands Guilder", "AED"))
            currencyItemList.add(CurrencyItem("🇳🇮 Nicaraguan Cordoba", "AED"))
            currencyItemList.add(CurrencyItem("🇳🇬 Nigerian Naira", "AED"))
            currencyItemList.add(CurrencyItem("🇳🇴 Norwegian Krone", "AED"))
            currencyItemList.add(CurrencyItem("🇴🇲 Omani Rial", "AED"))
            currencyItemList.add(CurrencyItem("🇵🇰 Pakistani Rupee", "AED"))
            currencyItemList.add(CurrencyItem("🇵🇦 Panamanian Balboa", "AED"))
            currencyItemList.add(CurrencyItem("🇵🇬 Papua New Guinean Kina", "AED"))
            currencyItemList.add(CurrencyItem("🇵🇾 Paraguayan Guarani", "AED"))
            currencyItemList.add(CurrencyItem("🇵🇪 Peruvian Sol", "AED"))
            currencyItemList.add(CurrencyItem("🇵🇭 Philippine Peso", "AED"))
            currencyItemList.add(CurrencyItem("🇵🇱 Polish Zloty", "AED"))
            currencyItemList.add(CurrencyItem("🇶🇦 Qatari Riyal", "AED"))
            currencyItemList.add(CurrencyItem("🇷🇴 Romanian Leu", "AED"))
            currencyItemList.add(CurrencyItem("🇷🇺 Russian Rubles", "AED"))
            currencyItemList.add(CurrencyItem("🇷🇼 Rwandan Franc", "AED"))
            currencyItemList.add(CurrencyItem("🇿🇦 South African Rand", "AED"))
            currencyItemList.add(CurrencyItem("🇰🇷 South Korea Won", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇸 South Sudanese Pound", "AED"))
            currencyItemList.add(CurrencyItem("🇼🇸 Samoan Tala", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇦 Saudi Riyal", "AED"))
            currencyItemList.add(CurrencyItem("🇷🇸 Serbian Dinar", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇨 Seychellois Rupee", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇱 Sierra Leone", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇬 Singapore Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇧 Solomon Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇴 Somali Shilling", "AED"))
            currencyItemList.add(CurrencyItem("🇱🇰 Sri Lankan Rupee", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇩 Sudanese Pound", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇷 Surinamese Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇿 Swazi Lilangeni", "AED"))
            currencyItemList.add(CurrencyItem("🇨🇭 Swiss Franc", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇪 Swedish Krona", "AED"))
            currencyItemList.add(CurrencyItem("🇸🇾 Syrian Pound", "AED"))
            currencyItemList.add(CurrencyItem("🇹🇼 Taiwan Dollar", "AED"))
            currencyItemList.add(CurrencyItem("🇹🇯 Tajikistani Somoni", "AED"))
            currencyItemList.add(CurrencyItem("🇹🇿 Tanzanian Shilling", "AED"))
            currencyItemList.add(CurrencyItem("🇹🇭 Thai Baht", "AED"))
            currencyItemList.add(CurrencyItem("🇹🇴 Tongan Pa'anga", "AED"))
            currencyItemList.add(CurrencyItem("🇹🇳 Tunisian Dinar", "AED"))
            currencyItemList.add(CurrencyItem("🇹🇷 Turkish Lira", "AED"))
            currencyItemList.add(CurrencyItem("🇹🇲 Turkmeny Manat", "AED"))
            currencyItemList.add(CurrencyItem("🇦🇪 UAE Dirham", "AED"))
            currencyItemList.add(CurrencyItem("🇺🇬 Ugandan Shilling", "AED"))
            currencyItemList.add(CurrencyItem("🇺🇦 Ukrainian Hryvna", "AED"))
            currencyItemList.add(CurrencyItem("🇺🇾 Uruguayan Peso", "AED"))
            currencyItemList.add(CurrencyItem("🇺🇿 Uzbekistani Som", "AED"))
            currencyItemList.add(CurrencyItem("🇻🇺 Vanuatu Vatu", "AED"))
            currencyItemList.add(CurrencyItem("🇻🇪 Venezuelan Bolivar", "AED"))
            currencyItemList.add(CurrencyItem("🇻🇳 Vietnamese Dong", "AED"))
            currencyItemList.add(CurrencyItem("🇿🇦 West African Franc", "AED"))
            currencyItemList.add(CurrencyItem("🇾🇪 Yemeni Rial", "AED"))
            currencyItemList.add(CurrencyItem("🇿🇲 Zambian Kwacha", "AED"))
            return currencyItemList
        }
    }
}