package com.thecalcurate.android.model

import android.util.Log
import androidx.databinding.BaseObservable
import androidx.databinding.Bindable
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData

class CurrencyItem(
    val name: String,
    val code: String,
    val rate: Double = .0
) {
    //    private val _rate = MutableLiveData(.0)
    private val _isFavorite = MutableLiveData(false)

    //    val rate: LiveData<Double> = _rate
    var isFavorite: LiveData<Boolean> = _isFavorite
    var isFavorite2 = false

//    val rateStr: LiveData<String> = Transformations.map(rate) {
//        "%.4f".format(rate)
//    }

    fun getRateStr(): String {
        return if (rate == .0) "0"
        else "%.3f".format(rate)
    }

    fun toggleFavorite() {
        isFavorite2 = !isFavorite2
    }

    companion object {
        fun getList(): MutableList<CurrencyItem> {
            var currencyItemList: MutableList<CurrencyItem> = ArrayList()
            currencyItemList.add(CurrencyItem("🇺🇸 US Dollar", "USD"))
            currencyItemList.add(CurrencyItem("🇪🇺 Euro", "EUR"))
            currencyItemList.add(CurrencyItem("🇬🇧 British Pound", "GBP"))
            currencyItemList.add(CurrencyItem("🇦🇫 Afghan Afghani", "AFN"))
            currencyItemList.add(CurrencyItem("🇦🇱 Albanian Lek", "ALL"))
            currencyItemList.add(CurrencyItem("🇩🇿 Algerian Dinar", "DZD"))
            currencyItemList.add(CurrencyItem("🇦🇴 Angolan Kwanza", "AOA"))
            currencyItemList.add(CurrencyItem("🇦🇷 Argentine Peso", "ARS"))
            currencyItemList.add(CurrencyItem("🇦🇲 Armenian Dram", "AMD"))
            currencyItemList.add(CurrencyItem("🇦🇼 Aruban Florin", "AWG"))
            currencyItemList.add(CurrencyItem("🇦🇺 Australian Dollar", "AUD"))
            currencyItemList.add(CurrencyItem("🇦🇿 Azerbaijan Manat", "AZN"))
            currencyItemList.add(CurrencyItem("🇧🇸 Bahamian Dollar", "BSD"))
            currencyItemList.add(CurrencyItem("🇧🇭 Bahrain Dinar", "BHD"))
            currencyItemList.add(CurrencyItem("🇧🇩 Bangladesh Taka", "BDT"))
            currencyItemList.add(CurrencyItem("🇧🇧 Barbados Dollar", "BBD"))
            currencyItemList.add(CurrencyItem("🇧🇾 Belarusian Ruble", "BYN"))
            currencyItemList.add(CurrencyItem("🇧🇿 Belize Dollar", "BZD"))
            currencyItemList.add(CurrencyItem("🇧🇲 Bermudan Dollar", "BMD"))
            currencyItemList.add(CurrencyItem("🇧🇹 Bhutanese Ngultrum", "BTN"))
            currencyItemList.add(CurrencyItem("🇧🇴 Bolivian Boliviano", "BOB"))
            currencyItemList.add(CurrencyItem("🇧🇷 Brazilian Real", "BRL"))
            currencyItemList.add(CurrencyItem("🇧🇳 Brunei Dollar", "BND"))
            currencyItemList.add(CurrencyItem("🇧🇬 Bulgarian Lev", "BGN"))
            currencyItemList.add(CurrencyItem("🇧🇮 Burundian Franc", "BIF"))
            currencyItemList.add(CurrencyItem("🇨🇫 Central African Franc", "XAF"))
            currencyItemList.add(CurrencyItem("🇰🇭 Cambodian Riel", "KHR"))
            currencyItemList.add(CurrencyItem("🇨🇦 Canadian Dollar", "CAD"))
            currencyItemList.add(CurrencyItem("🇨🇻 Cape Verdean Escudo", "CVE"))
            currencyItemList.add(CurrencyItem("🇰🇾 Cayman Island Dollar", "KYD"))
            currencyItemList.add(CurrencyItem("🇨🇿 Czech Koruna", "CZK"))
            currencyItemList.add(CurrencyItem("🇨🇱 Chilean Peso", "CLP"))
            currencyItemList.add(CurrencyItem("🇨🇳 Chinese Yuan", "CNY"))
            currencyItemList.add(CurrencyItem("🇨🇴 Colombian Peso", "COP"))
            currencyItemList.add(CurrencyItem("🇰🇲 Comorian Franc", "KMF"))
            currencyItemList.add(CurrencyItem("🇨🇩 Congolese Franc", "CDF"))
            currencyItemList.add(CurrencyItem("🇨🇷 Costa Rican Colon", "CRC"))
            currencyItemList.add(CurrencyItem("🇭🇷 Croatian Kuna", "HRK"))
            currencyItemList.add(CurrencyItem("🇨🇺 Cuban Peso", "CUP"))
            currencyItemList.add(CurrencyItem("🇩🇰 Danish Krone", "DKK"))
            currencyItemList.add(CurrencyItem("🇩🇯 Djiboutian Franc", "DJF"))
            currencyItemList.add(CurrencyItem("🇸🇹 Dobra", "STN"))
            currencyItemList.add(CurrencyItem("🇩🇴 Dominican Peso", "DOP"))
            currencyItemList.add(CurrencyItem("🇦🇬 East Caribbean Dollar", "XCD"))
            currencyItemList.add(CurrencyItem("🇪🇬 Egyptian Pound", "EGP"))
            currencyItemList.add(CurrencyItem("🇪🇷 Eritrean Nakfa", "ERN"))
            currencyItemList.add(CurrencyItem("🇪🇹 Ethiopian Birr", "ETB"))
            currencyItemList.add(CurrencyItem("🇫🇯 Fiji Dollar", "FJD"))
            currencyItemList.add(CurrencyItem("🇬🇲 Gambian Dalasi", "GMD"))
            currencyItemList.add(CurrencyItem("🇬🇪 Georgian Lari", "GEL"))
            currencyItemList.add(CurrencyItem("🇬🇭 Ghanaian Cedi", "GHS"))
            currencyItemList.add(CurrencyItem("🇬🇮 Gibraltar Pound", "GIP"))
            currencyItemList.add(CurrencyItem("🇬🇹 Guatemalan Quetzal", "GTQ"))
            currencyItemList.add(CurrencyItem("🇬🇳 Guinean Franc", "GNF"))
            currencyItemList.add(CurrencyItem("🇬🇾 Guyanese Dollar", "GYD"))
            currencyItemList.add(CurrencyItem("🇭🇰 Hong Kong Dollar", "HKD"))
            currencyItemList.add(CurrencyItem("🇭🇹 Haitian Gourde", "HTG"))
            currencyItemList.add(CurrencyItem("🇭🇳 Honduran Lempira", "HNL"))
            currencyItemList.add(CurrencyItem("🇭🇺 Hungarian Forint", "HUF"))
            currencyItemList.add(CurrencyItem("🇮🇸 Iceland Króna", "ISK"))
            currencyItemList.add(CurrencyItem("🇮🇳 Indian Rupee", "INR"))
            currencyItemList.add(CurrencyItem("🇮🇩 Indonesian Rupiah", "IDR"))
            currencyItemList.add(CurrencyItem("🇮🇷 Iranian Rial", "IRR"))
            currencyItemList.add(CurrencyItem("🇮🇶 Iraq Dinar", "IQD"))
            currencyItemList.add(CurrencyItem("🇮🇱 Israel Shekel", "ILS"))
            currencyItemList.add(CurrencyItem("🇯🇲 Jamaican Dollar", "JMD"))
            currencyItemList.add(CurrencyItem("🇯🇴 Jordanian Dinar", "JOD"))
            currencyItemList.add(CurrencyItem("🇯🇵 Japanese Yen", "JPY"))
            currencyItemList.add(CurrencyItem("🇰🇿 Kazakhstan Tenge", "KZT"))
            currencyItemList.add(CurrencyItem("🇰🇪 Kenyan Shilling", "KES"))
            currencyItemList.add(CurrencyItem("🇰🇼 Kuwaiti Dinar", "KWD"))
            currencyItemList.add(CurrencyItem("🇰🇬 Kyrgyzstan Som", "KGS"))
            currencyItemList.add(CurrencyItem("🇱🇦 Lao Kip", "LAK"))
            currencyItemList.add(CurrencyItem("🇱🇧 Lebanese Pound", "LBP"))
            currencyItemList.add(CurrencyItem("🇱🇷 Liberian Dollar", "LRD"))
            currencyItemList.add(CurrencyItem("🇱🇾 Libyan Dinar", "LYD"))
            currencyItemList.add(CurrencyItem("🇲🇰 Macedonian Denar", "MKD"))
            currencyItemList.add(CurrencyItem("🇲🇬 Malagasy Ariary", "MGA"))
            currencyItemList.add(CurrencyItem("🇲🇼 Malawian Kwacha", "MWK"))
            currencyItemList.add(CurrencyItem("🇲🇾 Malaysian Ringgit", "MYR"))
            currencyItemList.add(CurrencyItem("🇲🇻 Maldivian Rufiyaa", "MVR"))
            currencyItemList.add(CurrencyItem("🇲🇺 Mauritian Rupee", "MUR"))
            currencyItemList.add(CurrencyItem("🇲🇷 Mauritanian Ouguiya", "MRU"))
            currencyItemList.add(CurrencyItem("🇲🇽 Mexican Peso", "MXN"))
            currencyItemList.add(CurrencyItem("🇲🇩 Moldovan Leu", "MDL"))
            currencyItemList.add(CurrencyItem("🇲🇳 Mongolian Tögrög", "MNT"))
            currencyItemList.add(CurrencyItem("🇲🇦 Moroccan Dirham", "MAD"))
            currencyItemList.add(CurrencyItem("🇲🇿 Mozambican Metical", "MZN"))
            currencyItemList.add(CurrencyItem("🇲🇲 Myanmar Burmese Kyat", "MMK"))
            currencyItemList.add(CurrencyItem("🇳🇿 New Zealand Dollar", "NZD"))
            currencyItemList.add(CurrencyItem("🇳🇦 Nambian Dollar", "NAD"))
            currencyItemList.add(CurrencyItem("🇳🇵 Nepalese Rupee", "NPR"))
            currencyItemList.add(CurrencyItem("🇳🇱 Netherlands Antillian Guilder", "ANG"))
            currencyItemList.add(CurrencyItem("🇳🇮 Nicaraguan Cordoba", "NIO"))
            currencyItemList.add(CurrencyItem("🇳🇬 Nigerian Naira", "NGN"))
            currencyItemList.add(CurrencyItem("🇳🇴 Norwegian Krone", "NOK"))
            currencyItemList.add(CurrencyItem("🇴🇲 Oman Rial", "OMR"))
            currencyItemList.add(CurrencyItem("🇵🇰 Pakistan Rupee", "PKR"))
            currencyItemList.add(CurrencyItem("🇵🇦 Panamanian Balboa", "PAB"))
            currencyItemList.add(CurrencyItem("🇵🇬 Papua New Guinean Kina", "PGK"))
            currencyItemList.add(CurrencyItem("🇵🇾 Paraguayan Guarani", "PYG"))
            currencyItemList.add(CurrencyItem("🇵🇪 Peruvian Sol", "PEN"))
            currencyItemList.add(CurrencyItem("🇵🇭 Philippine Peso", "PHP"))
            currencyItemList.add(CurrencyItem("🇵🇱 Polish Zloty", "PLN"))
            currencyItemList.add(CurrencyItem("🇶🇦 Qatar Riyal", "QAR"))
            currencyItemList.add(CurrencyItem("🇷🇴 Romanian Leu", "RON"))
            currencyItemList.add(CurrencyItem("🇷🇺 Russian Rubles", "RUB"))
            currencyItemList.add(CurrencyItem("🇷🇼 Rwandan Franc", "RWF"))
            currencyItemList.add(CurrencyItem("🇿🇦 South African Rand", "ZAR"))
            currencyItemList.add(CurrencyItem("🇰🇷 South Korea Won", "KRW"))
            currencyItemList.add(CurrencyItem("🇸🇸 South Sudanese Pound", "SSP"))
            currencyItemList.add(CurrencyItem("🇼🇸 Samoan Tala", "WST"))
            currencyItemList.add(CurrencyItem("🇸🇦 Saudi Riyal", "SAR"))
            currencyItemList.add(CurrencyItem("🇷🇸 Serbian Dinar", "RSD"))
            currencyItemList.add(CurrencyItem("🇸🇨 Seychellois Rupee", "SCR"))
            currencyItemList.add(CurrencyItem("🇸🇱 Sierra Leone", "SLE"))
            currencyItemList.add(CurrencyItem("🇸🇬 Singapore Dollar", "SGD"))
            currencyItemList.add(CurrencyItem("🇸🇧 Solomon Dollar", "SBD"))
            currencyItemList.add(CurrencyItem("🇸🇴 Somali Shilling", "SOS"))
            currencyItemList.add(CurrencyItem("🇱🇰 Sri Lanka Rupee", "LKR"))
            currencyItemList.add(CurrencyItem("🇸🇩 Sudanese Pound", "SDG"))
            currencyItemList.add(CurrencyItem("🇸🇷 Surinamese Dollar", "SRD"))
            currencyItemList.add(CurrencyItem("🇸🇿 Eswatini Lilangeni", "SZL"))
            currencyItemList.add(CurrencyItem("🇨🇭 Swiss Franc", "CHF"))
            currencyItemList.add(CurrencyItem("🇸🇪 Swedish Krona", "SEK"))
            currencyItemList.add(CurrencyItem("🇸🇾 Syrian Pound", "SYP"))
            currencyItemList.add(CurrencyItem("🇹🇼 Taiwan Dollar", "TWD"))
            currencyItemList.add(CurrencyItem("🇹🇯 Tajikistan Somoni", "TJS"))
            currencyItemList.add(CurrencyItem("🇹🇿 Tanzanian Shilling", "TZS"))
            currencyItemList.add(CurrencyItem("🇹🇭 Thai Baht", "THB"))
            currencyItemList.add(CurrencyItem("🇹🇴 Tongan Pa'anga", "TOP"))
            currencyItemList.add(CurrencyItem("🇹🇳 Tunisian Dinar", "TND"))
            currencyItemList.add(CurrencyItem("🇹🇷 Turkish Lira", "TRY"))
            currencyItemList.add(CurrencyItem("🇹🇲 Turkmenistan Manat", "TMT"))
            currencyItemList.add(CurrencyItem("🇦🇪 UAE Dirham", "AED"))
            currencyItemList.add(CurrencyItem("🇺🇬 Ugandan Shilling", "UGX"))
            currencyItemList.add(CurrencyItem("🇺🇦 Ukrainian Hryvna", "UAH"))
            currencyItemList.add(CurrencyItem("🇺🇾 Uruguayan Peso", "UYU"))
            currencyItemList.add(CurrencyItem("🇺🇿 Uzbekistan Som", "UZS"))
            currencyItemList.add(CurrencyItem("🇻🇺 Vanuatu Vatu", "VUV"))
            currencyItemList.add(CurrencyItem("🇻🇪 Venezuelan Bolivar", "VES"))
            currencyItemList.add(CurrencyItem("🇻🇳 Vietnamese Dong", "VND"))
            currencyItemList.add(CurrencyItem("🇿🇦 West African Franc", "XOF"))
            currencyItemList.add(CurrencyItem("🇾🇪 Yemen Rial", "YER"))
            currencyItemList.add(CurrencyItem("🇿🇲 Zambian Kwacha", "ZMW"))
            return currencyItemList
        }
    }
}